apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: example
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "app=redmine"
spec:
  type: LoadBalancer
  selector:
    app: redmine
  ports:
  - name: http
    port: 80
    targetPort: 3000
